---
services:
  perceived-temp-service:
    container_name: open-weather
    image: svenschmidt1502/open_weather:latest
    environment:
      - API_KEY=${API_KEY}
      - BROKER_IP=${BROKER_IP}
      - BROKER_PORT=${BROKER_PORT}
      - CLIENT_ID=${CLIENT_ID}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - TOPIC=${TOPIC}
    deploy:
      replicas: 1